version: '3'

services:
  hyperion:
    image: ghcr.io/nint8835/hyperioncs
    restart: always
    networks:
      - web
    expose:
      - 8000
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host: hyperion.bootleg.technology"
      traefik.port: 8000
      traefik.frontend.entryPoints: "https"
    env_file:
      - .env
    environment:
      - SQLALCHEMY_CONNECTION_URL=sqlite:////hyperion/hyperion.sqlite
    volumes:
      - ./data:/hyperion

networks:
  web:
    external: true
