// This file is auto-generated by @hey-api/openapi-ts
import { type DefaultError, type UseMutationOptions, queryOptions, useMutation, useQuery } from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  type Options,
  connectIntegration,
  createCurrency,
  createIntegration,
  createIntegrationToken,
  deleteIntegrationToken,
  disconnectIntegration,
  editCurrency,
  editIntegration,
  getCurrencyIntegrations,
  getCurrencyPermissions,
  getCurrentUser,
  getIntegration,
  listIntegrationTokens,
  listIntegrations,
} from '../sdk.gen';
import type {
  ConnectIntegrationData,
  ConnectIntegrationError,
  CreateCurrencyData,
  CreateCurrencyError,
  CreateCurrencyResponse,
  CreateIntegrationData,
  CreateIntegrationError,
  CreateIntegrationResponse,
  CreateIntegrationTokenData,
  CreateIntegrationTokenError,
  CreateIntegrationTokenResponse,
  DeleteIntegrationTokenData,
  DeleteIntegrationTokenError,
  DisconnectIntegrationData,
  DisconnectIntegrationError,
  EditCurrencyData,
  EditCurrencyError,
  EditCurrencyResponse,
  EditIntegrationData,
  EditIntegrationError,
  EditIntegrationResponse,
  GetCurrencyIntegrationsData,
  GetCurrencyIntegrationsError,
  GetCurrencyIntegrationsResponse,
  GetCurrencyPermissionsData,
  GetCurrencyPermissionsError,
  GetCurrencyPermissionsResponse,
  GetCurrentUserData,
  GetCurrentUserResponse,
  GetIntegrationData,
  GetIntegrationError,
  GetIntegrationResponse,
  ListIntegrationTokensData,
  ListIntegrationTokensError,
  ListIntegrationTokensResponse,
  ListIntegrationsData,
  ListIntegrationsError,
  ListIntegrationsResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getCurrentUserQueryKey = (options?: Options<GetCurrentUserData>) =>
  createQueryKey('getCurrentUser', options);

/**
 * Get Current User
 *
 * Retrieve the details of the current user.
 */
export const getCurrentUserOptions = (options?: Options<GetCurrentUserData>) =>
  queryOptions<GetCurrentUserResponse, DefaultError, GetCurrentUserResponse, ReturnType<typeof getCurrentUserQueryKey>>(
    {
      queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentUser({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getCurrentUserQueryKey(options),
    },
  );

/**
 * Get Current User
 *
 * Retrieve the details of the current user.
 */
export const useGetCurrentUserQuery = (options?: Options<GetCurrentUserData>) =>
  useQuery(getCurrentUserOptions(options));

export type MutationKey<TOptions extends Partial<Options>> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    tags?: ReadonlyArray<string>;
  },
];

const createMutationKey = <TOptions extends Partial<Options>>(
  id: string,
  options?: TOptions,
  tags?: ReadonlyArray<string>,
): [MutationKey<TOptions>[0]] => {
  const params: MutationKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  };
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const createCurrencyMutationKey = (options?: Partial<Options<CreateCurrencyData>>) =>
  createMutationKey('createCurrency', options);

/**
 * Create Currency
 *
 * Create a new currency.
 */
export const createCurrencyMutation = (
  options?: Partial<Options<CreateCurrencyData>>,
): UseMutationOptions<CreateCurrencyResponse, CreateCurrencyError, Options<CreateCurrencyData>> => {
  const mutationOptions: UseMutationOptions<
    CreateCurrencyResponse,
    CreateCurrencyError,
    Options<CreateCurrencyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createCurrency({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
    mutationKey: createCurrencyMutationKey(options),
  };
  return mutationOptions;
};

/**
 * Create Currency
 *
 * Create a new currency.
 */
export const useCreateCurrencyMutation = (
  mutationOptions?: Partial<
    Omit<UseMutationOptions<CreateCurrencyResponse, CreateCurrencyError, Options<CreateCurrencyData>>, 'mutationFn'>
  >,
) => useMutation({ ...createCurrencyMutation(), ...mutationOptions });

export const editCurrencyMutationKey = (options?: Partial<Options<EditCurrencyData>>) =>
  createMutationKey('editCurrency', options);

/**
 * Edit Currency
 *
 * Edit an existing currency.
 */
export const editCurrencyMutation = (
  options?: Partial<Options<EditCurrencyData>>,
): UseMutationOptions<EditCurrencyResponse, EditCurrencyError, Options<EditCurrencyData>> => {
  const mutationOptions: UseMutationOptions<EditCurrencyResponse, EditCurrencyError, Options<EditCurrencyData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await editCurrency({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
    mutationKey: editCurrencyMutationKey(options),
  };
  return mutationOptions;
};

/**
 * Edit Currency
 *
 * Edit an existing currency.
 */
export const useEditCurrencyMutation = (
  mutationOptions?: Partial<
    Omit<UseMutationOptions<EditCurrencyResponse, EditCurrencyError, Options<EditCurrencyData>>, 'mutationFn'>
  >,
) => useMutation({ ...editCurrencyMutation(), ...mutationOptions });

export const getCurrencyPermissionsQueryKey = (options: Options<GetCurrencyPermissionsData>) =>
  createQueryKey('getCurrencyPermissions', options);

/**
 * Get Currency Permissions
 *
 * Get the permissions the current user has on a given currency.
 */
export const getCurrencyPermissionsOptions = (options: Options<GetCurrencyPermissionsData>) =>
  queryOptions<
    GetCurrencyPermissionsResponse,
    GetCurrencyPermissionsError,
    GetCurrencyPermissionsResponse,
    ReturnType<typeof getCurrencyPermissionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrencyPermissions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCurrencyPermissionsQueryKey(options),
  });

/**
 * Get Currency Permissions
 *
 * Get the permissions the current user has on a given currency.
 */
export const useGetCurrencyPermissionsQuery = (options: Options<GetCurrencyPermissionsData>) =>
  useQuery(getCurrencyPermissionsOptions(options));

export const getCurrencyIntegrationsQueryKey = (options: Options<GetCurrencyIntegrationsData>) =>
  createQueryKey('getCurrencyIntegrations', options);

/**
 * Get Currency Integrations
 *
 * Get the integrations linked to a given currency.
 */
export const getCurrencyIntegrationsOptions = (options: Options<GetCurrencyIntegrationsData>) =>
  queryOptions<
    GetCurrencyIntegrationsResponse,
    GetCurrencyIntegrationsError,
    GetCurrencyIntegrationsResponse,
    ReturnType<typeof getCurrencyIntegrationsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrencyIntegrations({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCurrencyIntegrationsQueryKey(options),
  });

/**
 * Get Currency Integrations
 *
 * Get the integrations linked to a given currency.
 */
export const useGetCurrencyIntegrationsQuery = (options: Options<GetCurrencyIntegrationsData>) =>
  useQuery(getCurrencyIntegrationsOptions(options));

export const listIntegrationsQueryKey = (options?: Options<ListIntegrationsData>) =>
  createQueryKey('listIntegrations', options);

/**
 * List Integrations
 *
 * List integrations visible to the current user.
 */
export const listIntegrationsOptions = (options?: Options<ListIntegrationsData>) =>
  queryOptions<
    ListIntegrationsResponse,
    ListIntegrationsError,
    ListIntegrationsResponse,
    ReturnType<typeof listIntegrationsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listIntegrations({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listIntegrationsQueryKey(options),
  });

/**
 * List Integrations
 *
 * List integrations visible to the current user.
 */
export const useListIntegrationsQuery = (options?: Options<ListIntegrationsData>) =>
  useQuery(listIntegrationsOptions(options));

export const createIntegrationMutationKey = (options?: Partial<Options<CreateIntegrationData>>) =>
  createMutationKey('createIntegration', options);

/**
 * Create Integration
 *
 * Create a new integration.
 */
export const createIntegrationMutation = (
  options?: Partial<Options<CreateIntegrationData>>,
): UseMutationOptions<CreateIntegrationResponse, CreateIntegrationError, Options<CreateIntegrationData>> => {
  const mutationOptions: UseMutationOptions<
    CreateIntegrationResponse,
    CreateIntegrationError,
    Options<CreateIntegrationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createIntegration({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
    mutationKey: createIntegrationMutationKey(options),
  };
  return mutationOptions;
};

/**
 * Create Integration
 *
 * Create a new integration.
 */
export const useCreateIntegrationMutation = (
  mutationOptions?: Partial<
    Omit<
      UseMutationOptions<CreateIntegrationResponse, CreateIntegrationError, Options<CreateIntegrationData>>,
      'mutationFn'
    >
  >,
) => useMutation({ ...createIntegrationMutation(), ...mutationOptions });

export const getIntegrationQueryKey = (options: Options<GetIntegrationData>) =>
  createQueryKey('getIntegration', options);

/**
 * Get Integration
 *
 * Get a single integration visible to the current user.
 */
export const getIntegrationOptions = (options: Options<GetIntegrationData>) =>
  queryOptions<
    GetIntegrationResponse,
    GetIntegrationError,
    GetIntegrationResponse,
    ReturnType<typeof getIntegrationQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getIntegration({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getIntegrationQueryKey(options),
  });

/**
 * Get Integration
 *
 * Get a single integration visible to the current user.
 */
export const useGetIntegrationQuery = (options: Options<GetIntegrationData>) =>
  useQuery(getIntegrationOptions(options));

export const editIntegrationMutationKey = (options?: Partial<Options<EditIntegrationData>>) =>
  createMutationKey('editIntegration', options);

/**
 * Edit Integration
 *
 * Edit an integration's metadata.
 */
export const editIntegrationMutation = (
  options?: Partial<Options<EditIntegrationData>>,
): UseMutationOptions<EditIntegrationResponse, EditIntegrationError, Options<EditIntegrationData>> => {
  const mutationOptions: UseMutationOptions<
    EditIntegrationResponse,
    EditIntegrationError,
    Options<EditIntegrationData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await editIntegration({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
    mutationKey: editIntegrationMutationKey(options),
  };
  return mutationOptions;
};

/**
 * Edit Integration
 *
 * Edit an integration's metadata.
 */
export const useEditIntegrationMutation = (
  mutationOptions?: Partial<
    Omit<UseMutationOptions<EditIntegrationResponse, EditIntegrationError, Options<EditIntegrationData>>, 'mutationFn'>
  >,
) => useMutation({ ...editIntegrationMutation(), ...mutationOptions });

export const listIntegrationTokensQueryKey = (options: Options<ListIntegrationTokensData>) =>
  createQueryKey('listIntegrationTokens', options);

/**
 * List Integration Tokens
 *
 * List tokens for an integration.
 */
export const listIntegrationTokensOptions = (options: Options<ListIntegrationTokensData>) =>
  queryOptions<
    ListIntegrationTokensResponse,
    ListIntegrationTokensError,
    ListIntegrationTokensResponse,
    ReturnType<typeof listIntegrationTokensQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listIntegrationTokens({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listIntegrationTokensQueryKey(options),
  });

/**
 * List Integration Tokens
 *
 * List tokens for an integration.
 */
export const useListIntegrationTokensQuery = (options: Options<ListIntegrationTokensData>) =>
  useQuery(listIntegrationTokensOptions(options));

export const createIntegrationTokenMutationKey = (options?: Partial<Options<CreateIntegrationTokenData>>) =>
  createMutationKey('createIntegrationToken', options);

/**
 * Create Integration Token
 *
 * Create a new token for an integration.
 *
 * The token value is only returned in this response — it cannot be retrieved later.
 */
export const createIntegrationTokenMutation = (
  options?: Partial<Options<CreateIntegrationTokenData>>,
): UseMutationOptions<
  CreateIntegrationTokenResponse,
  CreateIntegrationTokenError,
  Options<CreateIntegrationTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateIntegrationTokenResponse,
    CreateIntegrationTokenError,
    Options<CreateIntegrationTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createIntegrationToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
    mutationKey: createIntegrationTokenMutationKey(options),
  };
  return mutationOptions;
};

/**
 * Create Integration Token
 *
 * Create a new token for an integration.
 *
 * The token value is only returned in this response — it cannot be retrieved later.
 */
export const useCreateIntegrationTokenMutation = (
  mutationOptions?: Partial<
    Omit<
      UseMutationOptions<
        CreateIntegrationTokenResponse,
        CreateIntegrationTokenError,
        Options<CreateIntegrationTokenData>
      >,
      'mutationFn'
    >
  >,
) => useMutation({ ...createIntegrationTokenMutation(), ...mutationOptions });

export const deleteIntegrationTokenMutationKey = (options?: Partial<Options<DeleteIntegrationTokenData>>) =>
  createMutationKey('deleteIntegrationToken', options);

/**
 * Delete Integration Token
 *
 * Delete an integration token.
 */
export const deleteIntegrationTokenMutation = (
  options?: Partial<Options<DeleteIntegrationTokenData>>,
): UseMutationOptions<unknown, DeleteIntegrationTokenError, Options<DeleteIntegrationTokenData>> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteIntegrationTokenError,
    Options<DeleteIntegrationTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteIntegrationToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
    mutationKey: deleteIntegrationTokenMutationKey(options),
  };
  return mutationOptions;
};

/**
 * Delete Integration Token
 *
 * Delete an integration token.
 */
export const useDeleteIntegrationTokenMutation = (
  mutationOptions?: Partial<
    Omit<UseMutationOptions<unknown, DeleteIntegrationTokenError, Options<DeleteIntegrationTokenData>>, 'mutationFn'>
  >,
) => useMutation({ ...deleteIntegrationTokenMutation(), ...mutationOptions });

export const connectIntegrationMutationKey = (options?: Partial<Options<ConnectIntegrationData>>) =>
  createMutationKey('connectIntegration', options);

/**
 * Connect Integration
 *
 * Connect an integration to a currency.
 */
export const connectIntegrationMutation = (
  options?: Partial<Options<ConnectIntegrationData>>,
): UseMutationOptions<unknown, ConnectIntegrationError, Options<ConnectIntegrationData>> => {
  const mutationOptions: UseMutationOptions<unknown, ConnectIntegrationError, Options<ConnectIntegrationData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await connectIntegration({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
    mutationKey: connectIntegrationMutationKey(options),
  };
  return mutationOptions;
};

/**
 * Connect Integration
 *
 * Connect an integration to a currency.
 */
export const useConnectIntegrationMutation = (
  mutationOptions?: Partial<
    Omit<UseMutationOptions<unknown, ConnectIntegrationError, Options<ConnectIntegrationData>>, 'mutationFn'>
  >,
) => useMutation({ ...connectIntegrationMutation(), ...mutationOptions });

export const disconnectIntegrationMutationKey = (options?: Partial<Options<DisconnectIntegrationData>>) =>
  createMutationKey('disconnectIntegration', options);

/**
 * Disconnect Integration
 *
 * Disconnect an integration from a currency.
 */
export const disconnectIntegrationMutation = (
  options?: Partial<Options<DisconnectIntegrationData>>,
): UseMutationOptions<unknown, DisconnectIntegrationError, Options<DisconnectIntegrationData>> => {
  const mutationOptions: UseMutationOptions<unknown, DisconnectIntegrationError, Options<DisconnectIntegrationData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await disconnectIntegration({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
    mutationKey: disconnectIntegrationMutationKey(options),
  };
  return mutationOptions;
};

/**
 * Disconnect Integration
 *
 * Disconnect an integration from a currency.
 */
export const useDisconnectIntegrationMutation = (
  mutationOptions?: Partial<
    Omit<UseMutationOptions<unknown, DisconnectIntegrationError, Options<DisconnectIntegrationData>>, 'mutationFn'>
  >,
) => useMutation({ ...disconnectIntegrationMutation(), ...mutationOptions });
