// This file is auto-generated by @hey-api/openapi-ts
import { type DefaultError, queryOptions, useQuery } from '@tanstack/react-query';

import { client } from '../client.gen';
import { type Options, getCurrency, listCurrencies } from '../sdk.gen';
import type {
  GetCurrencyData,
  GetCurrencyError,
  GetCurrencyResponse,
  ListCurrenciesData,
  ListCurrenciesResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const listCurrenciesQueryKey = (options?: Options<ListCurrenciesData>) =>
  createQueryKey('listCurrencies', options);

/**
 * List Currencies
 *
 * List all currencies.
 */
export const listCurrenciesOptions = (options?: Options<ListCurrenciesData>) =>
  queryOptions<ListCurrenciesResponse, DefaultError, ListCurrenciesResponse, ReturnType<typeof listCurrenciesQueryKey>>(
    {
      queryFn: async ({ queryKey, signal }) => {
        const { data } = await listCurrencies({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listCurrenciesQueryKey(options),
    },
  );

/**
 * List Currencies
 *
 * List all currencies.
 */
export const useListCurrenciesQuery = (options?: Options<ListCurrenciesData>) =>
  useQuery(listCurrenciesOptions(options));

export const getCurrencyQueryKey = (options: Options<GetCurrencyData>) => createQueryKey('getCurrency', options);

/**
 * Get Currency
 *
 * Get a currency by its shortcode.
 */
export const getCurrencyOptions = (options: Options<GetCurrencyData>) =>
  queryOptions<GetCurrencyResponse, GetCurrencyError, GetCurrencyResponse, ReturnType<typeof getCurrencyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getCurrency({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getCurrencyQueryKey(options),
  });

/**
 * Get Currency
 *
 * Get a currency by its shortcode.
 */
export const useGetCurrencyQuery = (options: Options<GetCurrencyData>) => useQuery(getCurrencyOptions(options));
