/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type CurrencySchema = {
  /**
   * The unique shortcode of the currency.
   */
  shortcode: string;
  /**
   * The full name of the currency.
   */
  name: string;
  /**
   * The singular form of the currency.
   */
  singular_form: string;
  /**
   * The plural form of the currency.
   */
  plural_form: string;
};

/**
 * A generic error response.
 */
export type ErrorResponseSchema = {
  /**
   * A description of the error.
   */
  detail: string;
};

export type HTTPValidationError = {
  detail?: ValidationError[];
};

export type ValidationError = {
  loc: (string | number)[];
  msg: string;
  type: string;
};
