// Generated by ts-to-zod
import { z } from "zod";

export const CurrencySchemaZod = z.object({
    shortcode: z.string(),
    name: z.string(),
    singular_form: z.string(),
    plural_form: z.string()
});
