// This file is auto-generated by @hey-api/openapi-ts
import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetCurrencyData,
  GetCurrencyErrors,
  GetCurrencyResponses,
  ListCurrenciesData,
  ListCurrenciesResponses,
} from './types.gen';
import { zGetCurrencyPath, zGetCurrencyResponse, zListCurrenciesResponse } from './zod.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List Currencies
 *
 * List all currencies.
 */
export const listCurrencies = <ThrowOnError extends boolean = false>(
  options?: Options<ListCurrenciesData, ThrowOnError>,
): RequestResult<ListCurrenciesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ListCurrenciesResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zListCurrenciesResponse.parseAsync(data),
    url: '/currencies/',
    ...options,
  });

/**
 * Get Currency
 *
 * Get a currency by its shortcode.
 */
export const getCurrency = <ThrowOnError extends boolean = false>(
  options: Options<GetCurrencyData, ThrowOnError>,
): RequestResult<GetCurrencyResponses, GetCurrencyErrors, ThrowOnError> =>
  (options.client ?? client).get<GetCurrencyResponses, GetCurrencyErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetCurrencyPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zGetCurrencyResponse.parseAsync(data),
    url: '/currencies/{shortcode}',
    ...options,
  });
