// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api/v1` | (string & {});
};

/**
 * CurrencySchema
 */
export type CurrencySchema = {
  /**
   * Shortcode
   *
   * The unique shortcode of the currency.
   */
  shortcode: string;
  /**
   * Name
   *
   * The full name of the currency.
   */
  name: string;
  /**
   * Singular Form
   *
   * The singular form of the currency.
   */
  singular_form: string;
  /**
   * Plural Form
   *
   * The plural form of the currency.
   */
  plural_form: string;
};

/**
 * ErrorResponseSchema
 *
 * A generic error response.
 */
export type ErrorResponseSchema = {
  /**
   * Detail
   *
   * A description of the error.
   */
  detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type ListCurrenciesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/currencies/';
};

export type ListCurrenciesResponses = {
  /**
   * Response List Currencies
   *
   * Successful Response
   */
  200: Array<CurrencySchema>;
};

export type ListCurrenciesResponse = ListCurrenciesResponses[keyof ListCurrenciesResponses];

export type GetCurrencyData = {
  body?: never;
  path: {
    /**
     * Shortcode
     */
    shortcode: string;
  };
  query?: never;
  url: '/currencies/{shortcode}';
};

export type GetCurrencyErrors = {
  /**
   * Currency Not Found
   */
  404: ErrorResponseSchema;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCurrencyError = GetCurrencyErrors[keyof GetCurrencyErrors];

export type GetCurrencyResponses = {
  /**
   * Successful Response
   */
  200: CurrencySchema;
};

export type GetCurrencyResponse = GetCurrencyResponses[keyof GetCurrencyResponses];
