// This file is auto-generated by @hey-api/openapi-ts
import * as z from 'zod';

/**
 * CurrencySchema
 */
export const zCurrencySchema = z.object({
  shortcode: z.string(),
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

/**
 * ErrorResponseSchema
 *
 * A generic error response.
 */
export const zErrorResponseSchema = z.object({
  detail: z.string(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
  input: z.unknown().optional(),
  ctx: z.record(z.string(), z.unknown()).optional(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

/**
 * Response List Currencies
 *
 * Successful Response
 */
export const zListCurrenciesResponse = z.array(zCurrencySchema);

export const zGetCurrencyPath = z.object({
  shortcode: z.string(),
});

/**
 * Successful Response
 */
export const zGetCurrencyResponse = zCurrencySchema;
