/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CurrenciesIndexRouteImport } from './routes/currencies/index'
import { Route as IntegrationsCreateRouteImport } from './routes/integrations/create'
import { Route as CurrenciesCreateRouteImport } from './routes/currencies/create'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as CurrenciesShortcodeIndexRouteImport } from './routes/currencies/$shortcode/index'
import { Route as CurrenciesShortcodeManageRouteImport } from './routes/currencies/$shortcode/manage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesIndexRoute = CurrenciesIndexRouteImport.update({
  id: '/currencies/',
  path: '/currencies/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsCreateRoute = IntegrationsCreateRouteImport.update({
  id: '/integrations/create',
  path: '/integrations/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesCreateRoute = CurrenciesCreateRouteImport.update({
  id: '/currencies/create',
  path: '/currencies/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrenciesShortcodeIndexRoute =
  CurrenciesShortcodeIndexRouteImport.update({
    id: '/currencies/$shortcode/',
    path: '/currencies/$shortcode/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CurrenciesShortcodeManageRoute =
  CurrenciesShortcodeManageRouteImport.update({
    id: '/currencies/$shortcode/manage',
    path: '/currencies/$shortcode/manage',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/currencies/create': typeof CurrenciesCreateRoute
  '/integrations/create': typeof IntegrationsCreateRoute
  '/currencies': typeof CurrenciesIndexRoute
  '/currencies/$shortcode/manage': typeof CurrenciesShortcodeManageRoute
  '/currencies/$shortcode': typeof CurrenciesShortcodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/currencies/create': typeof CurrenciesCreateRoute
  '/integrations/create': typeof IntegrationsCreateRoute
  '/currencies': typeof CurrenciesIndexRoute
  '/currencies/$shortcode/manage': typeof CurrenciesShortcodeManageRoute
  '/currencies/$shortcode': typeof CurrenciesShortcodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/currencies/create': typeof CurrenciesCreateRoute
  '/integrations/create': typeof IntegrationsCreateRoute
  '/currencies/': typeof CurrenciesIndexRoute
  '/currencies/$shortcode/manage': typeof CurrenciesShortcodeManageRoute
  '/currencies/$shortcode/': typeof CurrenciesShortcodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/logout'
    | '/currencies/create'
    | '/integrations/create'
    | '/currencies'
    | '/currencies/$shortcode/manage'
    | '/currencies/$shortcode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/logout'
    | '/currencies/create'
    | '/integrations/create'
    | '/currencies'
    | '/currencies/$shortcode/manage'
    | '/currencies/$shortcode'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/logout'
    | '/currencies/create'
    | '/integrations/create'
    | '/currencies/'
    | '/currencies/$shortcode/manage'
    | '/currencies/$shortcode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  CurrenciesCreateRoute: typeof CurrenciesCreateRoute
  IntegrationsCreateRoute: typeof IntegrationsCreateRoute
  CurrenciesIndexRoute: typeof CurrenciesIndexRoute
  CurrenciesShortcodeManageRoute: typeof CurrenciesShortcodeManageRoute
  CurrenciesShortcodeIndexRoute: typeof CurrenciesShortcodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies/': {
      id: '/currencies/'
      path: '/currencies'
      fullPath: '/currencies'
      preLoaderRoute: typeof CurrenciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/create': {
      id: '/integrations/create'
      path: '/integrations/create'
      fullPath: '/integrations/create'
      preLoaderRoute: typeof IntegrationsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies/create': {
      id: '/currencies/create'
      path: '/currencies/create'
      fullPath: '/currencies/create'
      preLoaderRoute: typeof CurrenciesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies/$shortcode/': {
      id: '/currencies/$shortcode/'
      path: '/currencies/$shortcode'
      fullPath: '/currencies/$shortcode'
      preLoaderRoute: typeof CurrenciesShortcodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currencies/$shortcode/manage': {
      id: '/currencies/$shortcode/manage'
      path: '/currencies/$shortcode/manage'
      fullPath: '/currencies/$shortcode/manage'
      preLoaderRoute: typeof CurrenciesShortcodeManageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  CurrenciesCreateRoute: CurrenciesCreateRoute,
  IntegrationsCreateRoute: IntegrationsCreateRoute,
  CurrenciesIndexRoute: CurrenciesIndexRoute,
  CurrenciesShortcodeManageRoute: CurrenciesShortcodeManageRoute,
  CurrenciesShortcodeIndexRoute: CurrenciesShortcodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
