/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export type CreateCurrencySchema = {
  /**
   * A unique shortcode to identify the currency.
   *
   * @pattern ^[A-Z0-9]{3,5}$
   */
  shortcode: string;
  /**
   * The full name of the currency.
   */
  name: string;
  /**
   * The singular form of the currency.
   */
  singular_form: string;
  /**
   * The plural form of the currency.
   */
  plural_form: string;
};

export type CreateIntegrationSchema = {
  /**
   * The name of the integration.
   */
  name: string;
  /**
   * A description of the integration.
   */
  description: string;
  /**
   * URL to the website for the integration.
   */
  url?: string | null;
};

export type CurrencyPermissionsSchema = {
  /**
   * Whether the user can edit the currency.
   *
   * @default false
   */
  edit?: boolean;
};

export type CurrencySchema = {
  /**
   * The unique shortcode of the currency.
   */
  shortcode: string;
  /**
   * The full name of the currency.
   */
  name: string;
  /**
   * The singular form of the currency.
   */
  singular_form: string;
  /**
   * The plural form of the currency.
   */
  plural_form: string;
};

export type EditCurrencySchema = {
  /**
   * The full name of the currency.
   */
  name: string;
  /**
   * The singular form of the currency.
   */
  singular_form: string;
  /**
   * The plural form of the currency.
   */
  plural_form: string;
};

/**
 * A generic error response.
 */
export type ErrorResponseSchema = {
  /**
   * A description of the error.
   */
  detail: string;
};

export type HTTPValidationError = {
  detail?: ValidationError[];
};

export type IntegrationSchema = {
  /**
   * The unique identifier of the integration.
   */
  id: string;
  /**
   * The name of the integration.
   */
  name: string;
  /**
   * A description of the integration.
   */
  description: string;
  /**
   * URL to the website for the integration.
   */
  url?: string | null;
  /**
   * Whether the integration is private.
   */
  private: boolean;
};

/**
 * Details of the currently authenticated user.
 */
export type SessionUser = {
  /**
   * Discord snowflake of the authenticated user.
   */
  id: string;
};

export type ValidationError = {
  loc: (string | number)[];
  msg: string;
  type: string;
};
