// Generated by ts-to-zod
import { z } from 'zod';

export const ConnectIntegrationSchemaZod = z.object({
  currency_shortcode: z.string(),
});

export const CreateCurrencySchemaZod = z.object({
  shortcode: z.string().regex(/^[A-Z0-9]{3,5}$/),
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

export const CreateIntegrationSchemaZod = z.object({
  name: z.string(),
  description: z.string(),
  url: z.string().optional().nullable(),
});

export const CurrencyPermissionsSchemaZod = z.object({
  edit: z.boolean().optional().default(false),
});

export const CurrencySchemaZod = z.object({
  shortcode: z.string(),
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

export const EditCurrencySchemaZod = z.object({
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

export const ErrorResponseSchemaZod = z.object({
  detail: z.string(),
});

export const ValidationErrorZod = z.object({
  loc: z.array(z.union([z.string(), z.number()])),
  msg: z.string(),
  type: z.string(),
});

export const IntegrationSchemaZod = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  url: z.string().optional().nullable(),
  private: z.boolean(),
});

export const SessionUserZod = z.object({
  id: z.string(),
});

export const HTTPValidationErrorZod = z.object({
  detail: z.array(ValidationErrorZod).optional(),
});
