/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export type PlaceholderSchema = {
  /**
   * @default This is a placeholder endpoint to ensure OpenAPI code generation works correctly.
   */
  message?: string;
};
