/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
import * as reactQuery from '@tanstack/react-query';

import { InternalContext, queryKeyFn, useInternalContext } from './internalContext';
import type * as Fetcher from './internalFetcher';
import { internalFetch } from './internalFetcher';
import type * as Schemas from './internalSchemas';
import { deepMerge } from './internalUtils';

type QueryFnOptions = {
  signal?: AbortController['signal'];
};

export type GetCurrentUserError = Fetcher.ErrorWrapper<undefined>;

export type GetCurrentUserVariables = InternalContext['fetcherOptions'];

/**
 * Retrieve the details of the current user.
 */
export const fetchGetCurrentUser = (variables: GetCurrentUserVariables, signal?: AbortSignal) =>
  internalFetch<Schemas.SessionUser | null, GetCurrentUserError, undefined, {}, {}, {}>({
    url: '/auth/me',
    method: 'get',
    ...variables,
    signal,
  });

/**
 * Retrieve the details of the current user.
 */
export function getCurrentUserQuery(variables: GetCurrentUserVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.SessionUser | null>;
};

export function getCurrentUserQuery(variables: GetCurrentUserVariables | reactQuery.SkipToken): {
  queryKey: reactQuery.QueryKey;
  queryFn: ((options: QueryFnOptions) => Promise<Schemas.SessionUser | null>) | reactQuery.SkipToken;
};

export function getCurrentUserQuery(variables: GetCurrentUserVariables | reactQuery.SkipToken) {
  return {
    queryKey: queryKeyFn({
      path: '/auth/me',
      operationId: 'getCurrentUser',
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) => fetchGetCurrentUser(variables, signal),
  };
}

/**
 * Retrieve the details of the current user.
 */
export const useSuspenseGetCurrentUser = <TData = Schemas.SessionUser | null>(
  variables: GetCurrentUserVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<Schemas.SessionUser | null, GetCurrentUserError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useSuspenseQuery<Schemas.SessionUser | null, GetCurrentUserError, TData>({
    ...getCurrentUserQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Retrieve the details of the current user.
 */
export const useGetCurrentUser = <TData = Schemas.SessionUser | null>(
  variables: GetCurrentUserVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<Schemas.SessionUser | null, GetCurrentUserError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useQuery<Schemas.SessionUser | null, GetCurrentUserError, TData>({
    ...getCurrentUserQuery(variables === reactQuery.skipToken ? variables : deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export type QueryOperation = {
  path: '/auth/me';
  operationId: 'getCurrentUser';
  variables: GetCurrentUserVariables | reactQuery.SkipToken;
};
