// Generated by ts-to-zod
import { z } from 'zod';

export const CreateCurrencySchemaZod = z.object({
  shortcode: z.string().regex(/^[A-Z0-9]{3,5}$/),
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

export const CurrencySchemaZod = z.object({
  shortcode: z.string(),
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

export const EditCurrencySchemaZod = z.object({
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

export const ErrorResponseSchemaZod = z.object({
  detail: z.string(),
});

export const ValidationErrorZod = z.object({
  loc: z.array(z.union([z.string(), z.number()])),
  msg: z.string(),
  type: z.string(),
});

export const SessionUserZod = z.object({
  id: z.string(),
});

export const HTTPValidationErrorZod = z.object({
  detail: z.array(ValidationErrorZod).optional(),
});
