/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
import * as reactQuery from '@tanstack/react-query';

import { type InternalContext, queryKeyFn, useInternalContext } from './internalContext';
import type * as Fetcher from './internalFetcher';
import { internalFetch } from './internalFetcher';
import type * as Schemas from './internalSchemas';
import { deepMerge } from './internalUtils';

type QueryFnOptions = {
  signal?: AbortController['signal'];
};

export type GetCurrentUserError = Fetcher.ErrorWrapper<undefined>;

export type GetCurrentUserResponse = Schemas.SessionUser | null;

export type GetCurrentUserVariables = InternalContext['fetcherOptions'];

/**
 * Retrieve the details of the current user.
 */
export const fetchGetCurrentUser = (variables: GetCurrentUserVariables, signal?: AbortSignal) =>
  internalFetch<GetCurrentUserResponse, GetCurrentUserError, undefined, {}, {}, {}>({
    url: '/auth/me',
    method: 'get',
    ...variables,
    signal,
  });

/**
 * Retrieve the details of the current user.
 */
export function getCurrentUserQuery(variables: GetCurrentUserVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<GetCurrentUserResponse>;
};

export function getCurrentUserQuery(variables: GetCurrentUserVariables | reactQuery.SkipToken): {
  queryKey: reactQuery.QueryKey;
  queryFn: ((options: QueryFnOptions) => Promise<GetCurrentUserResponse>) | reactQuery.SkipToken;
};

export function getCurrentUserQuery(variables: GetCurrentUserVariables | reactQuery.SkipToken) {
  return {
    queryKey: queryKeyFn({
      path: '/auth/me',
      operationId: 'getCurrentUser',
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) => fetchGetCurrentUser(variables, signal),
  };
}

/**
 * Retrieve the details of the current user.
 */
export const useSuspenseGetCurrentUser = <TData = GetCurrentUserResponse>(
  variables: GetCurrentUserVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<GetCurrentUserResponse, GetCurrentUserError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useSuspenseQuery<GetCurrentUserResponse, GetCurrentUserError, TData>({
    ...getCurrentUserQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Retrieve the details of the current user.
 */
export const useGetCurrentUser = <TData = GetCurrentUserResponse>(
  variables: GetCurrentUserVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<GetCurrentUserResponse, GetCurrentUserError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useQuery<GetCurrentUserResponse, GetCurrentUserError, TData>({
    ...getCurrentUserQuery(variables === reactQuery.skipToken ? variables : deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export type CreateCurrencyError = Fetcher.ErrorWrapper<
  | {
      status: 409;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 422;
      payload: Schemas.HTTPValidationError;
    }
>;

export type CreateCurrencyVariables = {
  body: Schemas.CreateCurrencySchema;
} & InternalContext['fetcherOptions'];

/**
 * Create a new currency.
 */
export const fetchCreateCurrency = (variables: CreateCurrencyVariables, signal?: AbortSignal) =>
  internalFetch<Schemas.CurrencySchema, CreateCurrencyError, Schemas.CreateCurrencySchema, {}, {}, {}>({
    url: '/api/internal/currencies/',
    method: 'post',
    ...variables,
    signal,
  });

/**
 * Create a new currency.
 */
export const useCreateCurrency = (
  options?: Omit<
    reactQuery.UseMutationOptions<Schemas.CurrencySchema, CreateCurrencyError, CreateCurrencyVariables>,
    'mutationFn'
  >,
) => {
  const { fetcherOptions } = useInternalContext();
  return reactQuery.useMutation<Schemas.CurrencySchema, CreateCurrencyError, CreateCurrencyVariables>({
    mutationFn: (variables: CreateCurrencyVariables) => fetchCreateCurrency(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type EditCurrencyPathParams = {
  shortcode: string;
};

export type EditCurrencyError = Fetcher.ErrorWrapper<
  | {
      status: 403;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 422;
      payload: Schemas.HTTPValidationError;
    }
>;

export type EditCurrencyVariables = {
  body: Schemas.EditCurrencySchema;
  pathParams: EditCurrencyPathParams;
} & InternalContext['fetcherOptions'];

/**
 * Edit an existing currency.
 */
export const fetchEditCurrency = (variables: EditCurrencyVariables, signal?: AbortSignal) =>
  internalFetch<Schemas.CurrencySchema, EditCurrencyError, Schemas.EditCurrencySchema, {}, {}, EditCurrencyPathParams>({
    url: '/api/internal/currencies/{shortcode}',
    method: 'patch',
    ...variables,
    signal,
  });

/**
 * Edit an existing currency.
 */
export const useEditCurrency = (
  options?: Omit<
    reactQuery.UseMutationOptions<Schemas.CurrencySchema, EditCurrencyError, EditCurrencyVariables>,
    'mutationFn'
  >,
) => {
  const { fetcherOptions } = useInternalContext();
  return reactQuery.useMutation<Schemas.CurrencySchema, EditCurrencyError, EditCurrencyVariables>({
    mutationFn: (variables: EditCurrencyVariables) => fetchEditCurrency(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GetCurrencyPermissionsPathParams = {
  shortcode: string;
};

export type GetCurrencyPermissionsError = Fetcher.ErrorWrapper<{
  status: 422;
  payload: Schemas.HTTPValidationError;
}>;

export type GetCurrencyPermissionsVariables = {
  pathParams: GetCurrencyPermissionsPathParams;
} & InternalContext['fetcherOptions'];

/**
 * Get the permissions the current user has on a given currency.
 */
export const fetchGetCurrencyPermissions = (variables: GetCurrencyPermissionsVariables, signal?: AbortSignal) =>
  internalFetch<
    Schemas.CurrencyPermissionsSchema,
    GetCurrencyPermissionsError,
    undefined,
    {},
    {},
    GetCurrencyPermissionsPathParams
  >({
    url: '/api/internal/currencies/{shortcode}/permissions',
    method: 'get',
    ...variables,
    signal,
  });

/**
 * Get the permissions the current user has on a given currency.
 */
export function getCurrencyPermissionsQuery(variables: GetCurrencyPermissionsVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.CurrencyPermissionsSchema>;
};

export function getCurrencyPermissionsQuery(variables: GetCurrencyPermissionsVariables | reactQuery.SkipToken): {
  queryKey: reactQuery.QueryKey;
  queryFn: ((options: QueryFnOptions) => Promise<Schemas.CurrencyPermissionsSchema>) | reactQuery.SkipToken;
};

export function getCurrencyPermissionsQuery(variables: GetCurrencyPermissionsVariables | reactQuery.SkipToken) {
  return {
    queryKey: queryKeyFn({
      path: '/api/internal/currencies/{shortcode}/permissions',
      operationId: 'getCurrencyPermissions',
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) => fetchGetCurrencyPermissions(variables, signal),
  };
}

/**
 * Get the permissions the current user has on a given currency.
 */
export const useSuspenseGetCurrencyPermissions = <TData = Schemas.CurrencyPermissionsSchema>(
  variables: GetCurrencyPermissionsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<Schemas.CurrencyPermissionsSchema, GetCurrencyPermissionsError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useSuspenseQuery<Schemas.CurrencyPermissionsSchema, GetCurrencyPermissionsError, TData>({
    ...getCurrencyPermissionsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Get the permissions the current user has on a given currency.
 */
export const useGetCurrencyPermissions = <TData = Schemas.CurrencyPermissionsSchema>(
  variables: GetCurrencyPermissionsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<Schemas.CurrencyPermissionsSchema, GetCurrencyPermissionsError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useQuery<Schemas.CurrencyPermissionsSchema, GetCurrencyPermissionsError, TData>({
    ...getCurrencyPermissionsQuery(
      variables === reactQuery.skipToken ? variables : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type GetCurrencyIntegrationsPathParams = {
  shortcode: string;
};

export type GetCurrencyIntegrationsError = Fetcher.ErrorWrapper<
  | {
      status: 403;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 422;
      payload: Schemas.HTTPValidationError;
    }
>;

export type GetCurrencyIntegrationsResponse = Schemas.IntegrationSchema[];

export type GetCurrencyIntegrationsVariables = {
  pathParams: GetCurrencyIntegrationsPathParams;
} & InternalContext['fetcherOptions'];

/**
 * Get the integrations linked to a given currency.
 */
export const fetchGetCurrencyIntegrations = (variables: GetCurrencyIntegrationsVariables, signal?: AbortSignal) =>
  internalFetch<
    GetCurrencyIntegrationsResponse,
    GetCurrencyIntegrationsError,
    undefined,
    {},
    {},
    GetCurrencyIntegrationsPathParams
  >({
    url: '/api/internal/currencies/{shortcode}/integrations',
    method: 'get',
    ...variables,
    signal,
  });

/**
 * Get the integrations linked to a given currency.
 */
export function getCurrencyIntegrationsQuery(variables: GetCurrencyIntegrationsVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<GetCurrencyIntegrationsResponse>;
};

export function getCurrencyIntegrationsQuery(variables: GetCurrencyIntegrationsVariables | reactQuery.SkipToken): {
  queryKey: reactQuery.QueryKey;
  queryFn: ((options: QueryFnOptions) => Promise<GetCurrencyIntegrationsResponse>) | reactQuery.SkipToken;
};

export function getCurrencyIntegrationsQuery(variables: GetCurrencyIntegrationsVariables | reactQuery.SkipToken) {
  return {
    queryKey: queryKeyFn({
      path: '/api/internal/currencies/{shortcode}/integrations',
      operationId: 'getCurrencyIntegrations',
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) => fetchGetCurrencyIntegrations(variables, signal),
  };
}

/**
 * Get the integrations linked to a given currency.
 */
export const useSuspenseGetCurrencyIntegrations = <TData = GetCurrencyIntegrationsResponse>(
  variables: GetCurrencyIntegrationsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<GetCurrencyIntegrationsResponse, GetCurrencyIntegrationsError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useSuspenseQuery<GetCurrencyIntegrationsResponse, GetCurrencyIntegrationsError, TData>({
    ...getCurrencyIntegrationsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Get the integrations linked to a given currency.
 */
export const useGetCurrencyIntegrations = <TData = GetCurrencyIntegrationsResponse>(
  variables: GetCurrencyIntegrationsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<GetCurrencyIntegrationsResponse, GetCurrencyIntegrationsError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useQuery<GetCurrencyIntegrationsResponse, GetCurrencyIntegrationsError, TData>({
    ...getCurrencyIntegrationsQuery(
      variables === reactQuery.skipToken ? variables : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type CreateIntegrationError = Fetcher.ErrorWrapper<{
  status: 422;
  payload: Schemas.HTTPValidationError;
}>;

export type CreateIntegrationVariables = {
  body: Schemas.CreateIntegrationSchema;
} & InternalContext['fetcherOptions'];

/**
 * Create a new integration.
 */
export const fetchCreateIntegration = (variables: CreateIntegrationVariables, signal?: AbortSignal) =>
  internalFetch<Schemas.IntegrationSchema, CreateIntegrationError, Schemas.CreateIntegrationSchema, {}, {}, {}>({
    url: '/api/internal/integrations/',
    method: 'post',
    ...variables,
    signal,
  });

/**
 * Create a new integration.
 */
export const useCreateIntegration = (
  options?: Omit<
    reactQuery.UseMutationOptions<Schemas.IntegrationSchema, CreateIntegrationError, CreateIntegrationVariables>,
    'mutationFn'
  >,
) => {
  const { fetcherOptions } = useInternalContext();
  return reactQuery.useMutation<Schemas.IntegrationSchema, CreateIntegrationError, CreateIntegrationVariables>({
    mutationFn: (variables: CreateIntegrationVariables) => fetchCreateIntegration(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type ListIntegrationsQueryParams = {
  /**
   * @default false
   */
  manageable?: boolean;
};

export type ListIntegrationsError = Fetcher.ErrorWrapper<{
  status: 422;
  payload: Schemas.HTTPValidationError;
}>;

export type ListIntegrationsResponse = Schemas.IntegrationSchema[];

export type ListIntegrationsVariables = {
  queryParams?: ListIntegrationsQueryParams;
} & InternalContext['fetcherOptions'];

/**
 * List integrations visible to the current user.
 *
 * When manageable=true, returns only integrations the user can edit.
 * Otherwise returns public integrations and integrations the user can connect.
 */
export const fetchListIntegrations = (variables: ListIntegrationsVariables, signal?: AbortSignal) =>
  internalFetch<ListIntegrationsResponse, ListIntegrationsError, undefined, {}, ListIntegrationsQueryParams, {}>({
    url: '/api/internal/integrations/',
    method: 'get',
    ...variables,
    signal,
  });

/**
 * List integrations visible to the current user.
 *
 * When manageable=true, returns only integrations the user can edit.
 * Otherwise returns public integrations and integrations the user can connect.
 */
export function listIntegrationsQuery(variables: ListIntegrationsVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<ListIntegrationsResponse>;
};

export function listIntegrationsQuery(variables: ListIntegrationsVariables | reactQuery.SkipToken): {
  queryKey: reactQuery.QueryKey;
  queryFn: ((options: QueryFnOptions) => Promise<ListIntegrationsResponse>) | reactQuery.SkipToken;
};

export function listIntegrationsQuery(variables: ListIntegrationsVariables | reactQuery.SkipToken) {
  return {
    queryKey: queryKeyFn({
      path: '/api/internal/integrations/',
      operationId: 'listIntegrations',
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) => fetchListIntegrations(variables, signal),
  };
}

/**
 * List integrations visible to the current user.
 *
 * When manageable=true, returns only integrations the user can edit.
 * Otherwise returns public integrations and integrations the user can connect.
 */
export const useSuspenseListIntegrations = <TData = ListIntegrationsResponse>(
  variables: ListIntegrationsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<ListIntegrationsResponse, ListIntegrationsError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useSuspenseQuery<ListIntegrationsResponse, ListIntegrationsError, TData>({
    ...listIntegrationsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * List integrations visible to the current user.
 *
 * When manageable=true, returns only integrations the user can edit.
 * Otherwise returns public integrations and integrations the user can connect.
 */
export const useListIntegrations = <TData = ListIntegrationsResponse>(
  variables: ListIntegrationsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<ListIntegrationsResponse, ListIntegrationsError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useQuery<ListIntegrationsResponse, ListIntegrationsError, TData>({
    ...listIntegrationsQuery(variables === reactQuery.skipToken ? variables : deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export type GetIntegrationPathParams = {
  integrationId: string;
};

export type GetIntegrationError = Fetcher.ErrorWrapper<
  | {
      status: 403;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 422;
      payload: Schemas.HTTPValidationError;
    }
>;

export type GetIntegrationVariables = {
  pathParams: GetIntegrationPathParams;
} & InternalContext['fetcherOptions'];

/**
 * Get a single integration visible to the current user.
 *
 * Public integrations are accessible to all authenticated users.
 * Private integrations require the View role.
 */
export const fetchGetIntegration = (variables: GetIntegrationVariables, signal?: AbortSignal) =>
  internalFetch<Schemas.IntegrationSchema, GetIntegrationError, undefined, {}, {}, GetIntegrationPathParams>({
    url: '/api/internal/integrations/{integrationId}',
    method: 'get',
    ...variables,
    signal,
  });

/**
 * Get a single integration visible to the current user.
 *
 * Public integrations are accessible to all authenticated users.
 * Private integrations require the View role.
 */
export function getIntegrationQuery(variables: GetIntegrationVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.IntegrationSchema>;
};

export function getIntegrationQuery(variables: GetIntegrationVariables | reactQuery.SkipToken): {
  queryKey: reactQuery.QueryKey;
  queryFn: ((options: QueryFnOptions) => Promise<Schemas.IntegrationSchema>) | reactQuery.SkipToken;
};

export function getIntegrationQuery(variables: GetIntegrationVariables | reactQuery.SkipToken) {
  return {
    queryKey: queryKeyFn({
      path: '/api/internal/integrations/{integrationId}',
      operationId: 'getIntegration',
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) => fetchGetIntegration(variables, signal),
  };
}

/**
 * Get a single integration visible to the current user.
 *
 * Public integrations are accessible to all authenticated users.
 * Private integrations require the View role.
 */
export const useSuspenseGetIntegration = <TData = Schemas.IntegrationSchema>(
  variables: GetIntegrationVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<Schemas.IntegrationSchema, GetIntegrationError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useSuspenseQuery<Schemas.IntegrationSchema, GetIntegrationError, TData>({
    ...getIntegrationQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Get a single integration visible to the current user.
 *
 * Public integrations are accessible to all authenticated users.
 * Private integrations require the View role.
 */
export const useGetIntegration = <TData = Schemas.IntegrationSchema>(
  variables: GetIntegrationVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<Schemas.IntegrationSchema, GetIntegrationError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useQuery<Schemas.IntegrationSchema, GetIntegrationError, TData>({
    ...getIntegrationQuery(variables === reactQuery.skipToken ? variables : deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export type EditIntegrationPathParams = {
  integrationId: string;
};

export type EditIntegrationError = Fetcher.ErrorWrapper<
  | {
      status: 403;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 422;
      payload: Schemas.HTTPValidationError;
    }
>;

export type EditIntegrationVariables = {
  body: Schemas.EditIntegrationSchema;
  pathParams: EditIntegrationPathParams;
} & InternalContext['fetcherOptions'];

/**
 * Edit an integration's metadata. Requires Edit role.
 */
export const fetchEditIntegration = (variables: EditIntegrationVariables, signal?: AbortSignal) =>
  internalFetch<
    Schemas.IntegrationSchema,
    EditIntegrationError,
    Schemas.EditIntegrationSchema,
    {},
    {},
    EditIntegrationPathParams
  >({
    url: '/api/internal/integrations/{integrationId}',
    method: 'patch',
    ...variables,
    signal,
  });

/**
 * Edit an integration's metadata. Requires Edit role.
 */
export const useEditIntegration = (
  options?: Omit<
    reactQuery.UseMutationOptions<Schemas.IntegrationSchema, EditIntegrationError, EditIntegrationVariables>,
    'mutationFn'
  >,
) => {
  const { fetcherOptions } = useInternalContext();
  return reactQuery.useMutation<Schemas.IntegrationSchema, EditIntegrationError, EditIntegrationVariables>({
    mutationFn: (variables: EditIntegrationVariables) => fetchEditIntegration(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type ListIntegrationTokensPathParams = {
  integrationId: string;
};

export type ListIntegrationTokensError = Fetcher.ErrorWrapper<
  | {
      status: 403;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 422;
      payload: Schemas.HTTPValidationError;
    }
>;

export type ListIntegrationTokensResponse = Schemas.IntegrationTokenSchema[];

export type ListIntegrationTokensVariables = {
  pathParams: ListIntegrationTokensPathParams;
} & InternalContext['fetcherOptions'];

/**
 * List tokens for an integration. Requires Edit role.
 */
export const fetchListIntegrationTokens = (variables: ListIntegrationTokensVariables, signal?: AbortSignal) =>
  internalFetch<
    ListIntegrationTokensResponse,
    ListIntegrationTokensError,
    undefined,
    {},
    {},
    ListIntegrationTokensPathParams
  >({
    url: '/api/internal/integrations/{integrationId}/tokens',
    method: 'get',
    ...variables,
    signal,
  });

/**
 * List tokens for an integration. Requires Edit role.
 */
export function listIntegrationTokensQuery(variables: ListIntegrationTokensVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<ListIntegrationTokensResponse>;
};

export function listIntegrationTokensQuery(variables: ListIntegrationTokensVariables | reactQuery.SkipToken): {
  queryKey: reactQuery.QueryKey;
  queryFn: ((options: QueryFnOptions) => Promise<ListIntegrationTokensResponse>) | reactQuery.SkipToken;
};

export function listIntegrationTokensQuery(variables: ListIntegrationTokensVariables | reactQuery.SkipToken) {
  return {
    queryKey: queryKeyFn({
      path: '/api/internal/integrations/{integrationId}/tokens',
      operationId: 'listIntegrationTokens',
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) => fetchListIntegrationTokens(variables, signal),
  };
}

/**
 * List tokens for an integration. Requires Edit role.
 */
export const useSuspenseListIntegrationTokens = <TData = ListIntegrationTokensResponse>(
  variables: ListIntegrationTokensVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<ListIntegrationTokensResponse, ListIntegrationTokensError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useSuspenseQuery<ListIntegrationTokensResponse, ListIntegrationTokensError, TData>({
    ...listIntegrationTokensQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * List tokens for an integration. Requires Edit role.
 */
export const useListIntegrationTokens = <TData = ListIntegrationTokensResponse>(
  variables: ListIntegrationTokensVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<ListIntegrationTokensResponse, ListIntegrationTokensError, TData>,
    'queryKey' | 'queryFn' | 'initialData'
  >,
) => {
  const { queryOptions, fetcherOptions } = useInternalContext(options);
  return reactQuery.useQuery<ListIntegrationTokensResponse, ListIntegrationTokensError, TData>({
    ...listIntegrationTokensQuery(
      variables === reactQuery.skipToken ? variables : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type CreateIntegrationTokenPathParams = {
  integrationId: string;
};

export type CreateIntegrationTokenError = Fetcher.ErrorWrapper<
  | {
      status: 403;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 422;
      payload: Schemas.HTTPValidationError;
    }
>;

export type CreateIntegrationTokenVariables = {
  body: Schemas.CreateIntegrationTokenSchema;
  pathParams: CreateIntegrationTokenPathParams;
} & InternalContext['fetcherOptions'];

/**
 * Create a new token for an integration. Requires Edit role.
 *
 * The token value is only returned in this response — it cannot be retrieved later.
 */
export const fetchCreateIntegrationToken = (variables: CreateIntegrationTokenVariables, signal?: AbortSignal) =>
  internalFetch<
    Schemas.CreatedIntegrationTokenSchema,
    CreateIntegrationTokenError,
    Schemas.CreateIntegrationTokenSchema,
    {},
    {},
    CreateIntegrationTokenPathParams
  >({
    url: '/api/internal/integrations/{integrationId}/tokens',
    method: 'post',
    ...variables,
    signal,
  });

/**
 * Create a new token for an integration. Requires Edit role.
 *
 * The token value is only returned in this response — it cannot be retrieved later.
 */
export const useCreateIntegrationToken = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.CreatedIntegrationTokenSchema,
      CreateIntegrationTokenError,
      CreateIntegrationTokenVariables
    >,
    'mutationFn'
  >,
) => {
  const { fetcherOptions } = useInternalContext();
  return reactQuery.useMutation<
    Schemas.CreatedIntegrationTokenSchema,
    CreateIntegrationTokenError,
    CreateIntegrationTokenVariables
  >({
    mutationFn: (variables: CreateIntegrationTokenVariables) =>
      fetchCreateIntegrationToken(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type DeleteIntegrationTokenPathParams = {
  integrationId: string;
  tokenId: string;
};

export type DeleteIntegrationTokenError = Fetcher.ErrorWrapper<
  | {
      status: 403;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 404;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 422;
      payload: Schemas.HTTPValidationError;
    }
>;

export type DeleteIntegrationTokenVariables = {
  pathParams: DeleteIntegrationTokenPathParams;
} & InternalContext['fetcherOptions'];

/**
 * Delete an integration token. Requires Edit role.
 */
export const fetchDeleteIntegrationToken = (variables: DeleteIntegrationTokenVariables, signal?: AbortSignal) =>
  internalFetch<void, DeleteIntegrationTokenError, undefined, {}, {}, DeleteIntegrationTokenPathParams>({
    url: '/api/internal/integrations/{integrationId}/tokens/{tokenId}',
    method: 'delete',
    ...variables,
    signal,
  });

/**
 * Delete an integration token. Requires Edit role.
 */
export const useDeleteIntegrationToken = (
  options?: Omit<
    reactQuery.UseMutationOptions<void, DeleteIntegrationTokenError, DeleteIntegrationTokenVariables>,
    'mutationFn'
  >,
) => {
  const { fetcherOptions } = useInternalContext();
  return reactQuery.useMutation<void, DeleteIntegrationTokenError, DeleteIntegrationTokenVariables>({
    mutationFn: (variables: DeleteIntegrationTokenVariables) =>
      fetchDeleteIntegrationToken(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type ConnectIntegrationPathParams = {
  integrationId: string;
};

export type ConnectIntegrationError = Fetcher.ErrorWrapper<
  | {
      status: 403;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 409;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 422;
      payload: Schemas.HTTPValidationError;
    }
>;

export type ConnectIntegrationVariables = {
  body: Schemas.ConnectIntegrationSchema;
  pathParams: ConnectIntegrationPathParams;
} & InternalContext['fetcherOptions'];

/**
 * Connect an integration to a currency.
 */
export const fetchConnectIntegration = (variables: ConnectIntegrationVariables, signal?: AbortSignal) =>
  internalFetch<void, ConnectIntegrationError, Schemas.ConnectIntegrationSchema, {}, {}, ConnectIntegrationPathParams>({
    url: '/api/internal/integrations/{integrationId}/connect',
    method: 'post',
    ...variables,
    signal,
  });

/**
 * Connect an integration to a currency.
 */
export const useConnectIntegration = (
  options?: Omit<
    reactQuery.UseMutationOptions<void, ConnectIntegrationError, ConnectIntegrationVariables>,
    'mutationFn'
  >,
) => {
  const { fetcherOptions } = useInternalContext();
  return reactQuery.useMutation<void, ConnectIntegrationError, ConnectIntegrationVariables>({
    mutationFn: (variables: ConnectIntegrationVariables) =>
      fetchConnectIntegration(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type DisconnectIntegrationPathParams = {
  integrationId: string;
};

export type DisconnectIntegrationError = Fetcher.ErrorWrapper<
  | {
      status: 403;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 409;
      payload: Schemas.ErrorResponseSchema;
    }
  | {
      status: 422;
      payload: Schemas.HTTPValidationError;
    }
>;

export type DisconnectIntegrationVariables = {
  body: Schemas.ConnectIntegrationSchema;
  pathParams: DisconnectIntegrationPathParams;
} & InternalContext['fetcherOptions'];

/**
 * Disconnect an integration from a currency.
 */
export const fetchDisconnectIntegration = (variables: DisconnectIntegrationVariables, signal?: AbortSignal) =>
  internalFetch<
    void,
    DisconnectIntegrationError,
    Schemas.ConnectIntegrationSchema,
    {},
    {},
    DisconnectIntegrationPathParams
  >({
    url: '/api/internal/integrations/{integrationId}/disconnect',
    method: 'post',
    ...variables,
    signal,
  });

/**
 * Disconnect an integration from a currency.
 */
export const useDisconnectIntegration = (
  options?: Omit<
    reactQuery.UseMutationOptions<void, DisconnectIntegrationError, DisconnectIntegrationVariables>,
    'mutationFn'
  >,
) => {
  const { fetcherOptions } = useInternalContext();
  return reactQuery.useMutation<void, DisconnectIntegrationError, DisconnectIntegrationVariables>({
    mutationFn: (variables: DisconnectIntegrationVariables) =>
      fetchDisconnectIntegration(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type QueryOperation =
  | {
      path: '/auth/me';
      operationId: 'getCurrentUser';
      variables: GetCurrentUserVariables | reactQuery.SkipToken;
    }
  | {
      path: '/api/internal/currencies/{shortcode}/permissions';
      operationId: 'getCurrencyPermissions';
      variables: GetCurrencyPermissionsVariables | reactQuery.SkipToken;
    }
  | {
      path: '/api/internal/currencies/{shortcode}/integrations';
      operationId: 'getCurrencyIntegrations';
      variables: GetCurrencyIntegrationsVariables | reactQuery.SkipToken;
    }
  | {
      path: '/api/internal/integrations/';
      operationId: 'listIntegrations';
      variables: ListIntegrationsVariables | reactQuery.SkipToken;
    }
  | {
      path: '/api/internal/integrations/{integrationId}';
      operationId: 'getIntegration';
      variables: GetIntegrationVariables | reactQuery.SkipToken;
    }
  | {
      path: '/api/internal/integrations/{integrationId}/tokens';
      operationId: 'listIntegrationTokens';
      variables: ListIntegrationTokensVariables | reactQuery.SkipToken;
    };
