// Generated by ts-to-zod
import { z } from 'zod';

export const createCurrencySchemaSchema = z.object({
  shortcode: z.string().regex(/^[A-Z0-9]{3,5}$/),
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

export const currencySchemaSchema = z.object({
  shortcode: z.string(),
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

export const errorResponseSchemaSchema = z.object({
  detail: z.string(),
});

export const validationErrorSchema = z.object({
  loc: z.array(z.union([z.string(), z.number()])),
  msg: z.string(),
  type: z.string(),
});

export const sessionUserSchema = z.object({
  id: z.string(),
});

export const hTTPValidationErrorSchema = z.object({
  detail: z.array(validationErrorSchema).optional(),
});
