// This file is auto-generated by @hey-api/openapi-ts
import * as z from 'zod';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
  ConnectIntegrationData,
  ConnectIntegrationErrors,
  ConnectIntegrationResponses,
  CreateCurrencyData,
  CreateCurrencyErrors,
  CreateCurrencyResponses,
  CreateIntegrationData,
  CreateIntegrationErrors,
  CreateIntegrationResponses,
  CreateIntegrationTokenData,
  CreateIntegrationTokenErrors,
  CreateIntegrationTokenResponses,
  DeleteIntegrationTokenData,
  DeleteIntegrationTokenErrors,
  DeleteIntegrationTokenResponses,
  DisconnectIntegrationData,
  DisconnectIntegrationErrors,
  DisconnectIntegrationResponses,
  EditCurrencyData,
  EditCurrencyErrors,
  EditCurrencyResponses,
  EditIntegrationData,
  EditIntegrationErrors,
  EditIntegrationResponses,
  GetCurrencyIntegrationsData,
  GetCurrencyIntegrationsErrors,
  GetCurrencyIntegrationsResponses,
  GetCurrencyPermissionsData,
  GetCurrencyPermissionsErrors,
  GetCurrencyPermissionsResponses,
  GetCurrentUserData,
  GetCurrentUserResponses,
  GetIntegrationData,
  GetIntegrationErrors,
  GetIntegrationResponses,
  ListIntegrationTokensData,
  ListIntegrationTokensErrors,
  ListIntegrationTokensResponses,
  ListIntegrationsData,
  ListIntegrationsErrors,
  ListIntegrationsResponses,
} from './types.gen';
import {
  zConnectIntegrationBody,
  zConnectIntegrationPath,
  zCreateCurrencyBody,
  zCreateCurrencyResponse,
  zCreateIntegrationBody,
  zCreateIntegrationResponse,
  zCreateIntegrationTokenBody,
  zCreateIntegrationTokenPath,
  zCreateIntegrationTokenResponse,
  zDeleteIntegrationTokenPath,
  zDisconnectIntegrationBody,
  zDisconnectIntegrationPath,
  zEditCurrencyBody,
  zEditCurrencyPath,
  zEditCurrencyResponse,
  zEditIntegrationBody,
  zEditIntegrationPath,
  zEditIntegrationResponse,
  zGetCurrencyIntegrationsPath,
  zGetCurrencyIntegrationsResponse,
  zGetCurrencyPermissionsPath,
  zGetCurrencyPermissionsResponse,
  zGetCurrentUserResponse,
  zGetIntegrationPath,
  zGetIntegrationResponse,
  zListIntegrationTokensPath,
  zListIntegrationTokensResponse,
  zListIntegrationsQuery,
  zListIntegrationsResponse,
} from './zod.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get Current User
 *
 * Retrieve the details of the current user.
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentUserData, ThrowOnError>,
): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetCurrentUserResponses, unknown, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zGetCurrentUserResponse.parseAsync(data),
    url: '/auth/me',
    ...options,
  });

/**
 * Create Currency
 *
 * Create a new currency.
 */
export const createCurrency = <ThrowOnError extends boolean = false>(
  options: Options<CreateCurrencyData, ThrowOnError>,
): RequestResult<CreateCurrencyResponses, CreateCurrencyErrors, ThrowOnError> =>
  (options.client ?? client).post<CreateCurrencyResponses, CreateCurrencyErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateCurrencyBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zCreateCurrencyResponse.parseAsync(data),
    url: '/api/internal/currencies/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Edit Currency
 *
 * Edit an existing currency.
 */
export const editCurrency = <ThrowOnError extends boolean = false>(
  options: Options<EditCurrencyData, ThrowOnError>,
): RequestResult<EditCurrencyResponses, EditCurrencyErrors, ThrowOnError> =>
  (options.client ?? client).patch<EditCurrencyResponses, EditCurrencyErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zEditCurrencyBody,
          path: zEditCurrencyPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zEditCurrencyResponse.parseAsync(data),
    url: '/api/internal/currencies/{shortcode}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Currency Permissions
 *
 * Get the permissions the current user has on a given currency.
 */
export const getCurrencyPermissions = <ThrowOnError extends boolean = false>(
  options: Options<GetCurrencyPermissionsData, ThrowOnError>,
): RequestResult<GetCurrencyPermissionsResponses, GetCurrencyPermissionsErrors, ThrowOnError> =>
  (options.client ?? client).get<GetCurrencyPermissionsResponses, GetCurrencyPermissionsErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetCurrencyPermissionsPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zGetCurrencyPermissionsResponse.parseAsync(data),
    url: '/api/internal/currencies/{shortcode}/permissions',
    ...options,
  });

/**
 * Get Currency Integrations
 *
 * Get the integrations linked to a given currency.
 */
export const getCurrencyIntegrations = <ThrowOnError extends boolean = false>(
  options: Options<GetCurrencyIntegrationsData, ThrowOnError>,
): RequestResult<GetCurrencyIntegrationsResponses, GetCurrencyIntegrationsErrors, ThrowOnError> =>
  (options.client ?? client).get<GetCurrencyIntegrationsResponses, GetCurrencyIntegrationsErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetCurrencyIntegrationsPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zGetCurrencyIntegrationsResponse.parseAsync(data),
    url: '/api/internal/currencies/{shortcode}/integrations',
    ...options,
  });

/**
 * List Integrations
 *
 * List integrations visible to the current user.
 */
export const listIntegrations = <ThrowOnError extends boolean = false>(
  options?: Options<ListIntegrationsData, ThrowOnError>,
): RequestResult<ListIntegrationsResponses, ListIntegrationsErrors, ThrowOnError> =>
  (options?.client ?? client).get<ListIntegrationsResponses, ListIntegrationsErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zListIntegrationsQuery.optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zListIntegrationsResponse.parseAsync(data),
    url: '/api/internal/integrations/',
    ...options,
  });

/**
 * Create Integration
 *
 * Create a new integration.
 */
export const createIntegration = <ThrowOnError extends boolean = false>(
  options: Options<CreateIntegrationData, ThrowOnError>,
): RequestResult<CreateIntegrationResponses, CreateIntegrationErrors, ThrowOnError> =>
  (options.client ?? client).post<CreateIntegrationResponses, CreateIntegrationErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateIntegrationBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zCreateIntegrationResponse.parseAsync(data),
    url: '/api/internal/integrations/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Integration
 *
 * Get a single integration visible to the current user.
 */
export const getIntegration = <ThrowOnError extends boolean = false>(
  options: Options<GetIntegrationData, ThrowOnError>,
): RequestResult<GetIntegrationResponses, GetIntegrationErrors, ThrowOnError> =>
  (options.client ?? client).get<GetIntegrationResponses, GetIntegrationErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zGetIntegrationPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zGetIntegrationResponse.parseAsync(data),
    url: '/api/internal/integrations/{integration_id}',
    ...options,
  });

/**
 * Edit Integration
 *
 * Edit an integration's metadata.
 */
export const editIntegration = <ThrowOnError extends boolean = false>(
  options: Options<EditIntegrationData, ThrowOnError>,
): RequestResult<EditIntegrationResponses, EditIntegrationErrors, ThrowOnError> =>
  (options.client ?? client).patch<EditIntegrationResponses, EditIntegrationErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zEditIntegrationBody,
          path: zEditIntegrationPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zEditIntegrationResponse.parseAsync(data),
    url: '/api/internal/integrations/{integration_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Integration Tokens
 *
 * List tokens for an integration.
 */
export const listIntegrationTokens = <ThrowOnError extends boolean = false>(
  options: Options<ListIntegrationTokensData, ThrowOnError>,
): RequestResult<ListIntegrationTokensResponses, ListIntegrationTokensErrors, ThrowOnError> =>
  (options.client ?? client).get<ListIntegrationTokensResponses, ListIntegrationTokensErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zListIntegrationTokensPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zListIntegrationTokensResponse.parseAsync(data),
    url: '/api/internal/integrations/{integration_id}/tokens',
    ...options,
  });

/**
 * Create Integration Token
 *
 * Create a new token for an integration.
 *
 * The token value is only returned in this response — it cannot be retrieved later.
 */
export const createIntegrationToken = <ThrowOnError extends boolean = false>(
  options: Options<CreateIntegrationTokenData, ThrowOnError>,
): RequestResult<CreateIntegrationTokenResponses, CreateIntegrationTokenErrors, ThrowOnError> =>
  (options.client ?? client).post<CreateIntegrationTokenResponses, CreateIntegrationTokenErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateIntegrationTokenBody,
          path: zCreateIntegrationTokenPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    responseValidator: async (data) => await zCreateIntegrationTokenResponse.parseAsync(data),
    url: '/api/internal/integrations/{integration_id}/tokens',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Integration Token
 *
 * Delete an integration token.
 */
export const deleteIntegrationToken = <ThrowOnError extends boolean = false>(
  options: Options<DeleteIntegrationTokenData, ThrowOnError>,
): RequestResult<DeleteIntegrationTokenResponses, DeleteIntegrationTokenErrors, ThrowOnError> =>
  (options.client ?? client).delete<DeleteIntegrationTokenResponses, DeleteIntegrationTokenErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: zDeleteIntegrationTokenPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: '/api/internal/integrations/{integration_id}/tokens/{token_id}',
    ...options,
  });

/**
 * Connect Integration
 *
 * Connect an integration to a currency.
 */
export const connectIntegration = <ThrowOnError extends boolean = false>(
  options: Options<ConnectIntegrationData, ThrowOnError>,
): RequestResult<ConnectIntegrationResponses, ConnectIntegrationErrors, ThrowOnError> =>
  (options.client ?? client).post<ConnectIntegrationResponses, ConnectIntegrationErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zConnectIntegrationBody,
          path: zConnectIntegrationPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: '/api/internal/integrations/{integration_id}/connect',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Disconnect Integration
 *
 * Disconnect an integration from a currency.
 */
export const disconnectIntegration = <ThrowOnError extends boolean = false>(
  options: Options<DisconnectIntegrationData, ThrowOnError>,
): RequestResult<DisconnectIntegrationResponses, DisconnectIntegrationErrors, ThrowOnError> =>
  (options.client ?? client).post<DisconnectIntegrationResponses, DisconnectIntegrationErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zDisconnectIntegrationBody,
          path: zDisconnectIntegrationPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: '/api/internal/integrations/{integration_id}/disconnect',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
