// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ConnectIntegrationSchema
 */
export type ConnectIntegrationSchema = {
  /**
   * Currency Shortcode
   *
   * The shortcode of the currency to connect the integration to.
   */
  currency_shortcode: string;
};

/**
 * CreateCurrencySchema
 */
export type CreateCurrencySchema = {
  /**
   * Shortcode
   *
   * A unique shortcode to identify the currency.
   */
  shortcode: string;
  /**
   * Name
   *
   * The full name of the currency.
   */
  name: string;
  /**
   * Singular Form
   *
   * The singular form of the currency.
   */
  singular_form: string;
  /**
   * Plural Form
   *
   * The plural form of the currency.
   */
  plural_form: string;
};

/**
 * CreateIntegrationSchema
 */
export type CreateIntegrationSchema = {
  /**
   * Name
   *
   * The name of the integration.
   */
  name: string;
  /**
   * Description
   *
   * A description of the integration.
   */
  description: string;
  /**
   * Url
   *
   * URL to the website for the integration.
   */
  url?: string | null;
};

/**
 * CreateIntegrationTokenSchema
 */
export type CreateIntegrationTokenSchema = {
  /**
   * Name
   *
   * The name of the token.
   */
  name: string;
};

/**
 * CreatedIntegrationTokenSchema
 */
export type CreatedIntegrationTokenSchema = {
  /**
   * Id
   *
   * The unique identifier of the token.
   */
  id: string;
  /**
   * Name
   *
   * The name of the token.
   */
  name: string;
  /**
   * Token
   *
   * The JWT token value. Only returned at creation time.
   */
  token: string;
};

/**
 * CurrencyPermissionsSchema
 */
export type CurrencyPermissionsSchema = {
  /**
   * Edit
   *
   * Whether the user can edit the currency.
   */
  edit?: boolean;
};

/**
 * CurrencySchema
 */
export type CurrencySchema = {
  /**
   * Shortcode
   *
   * The unique shortcode of the currency.
   */
  shortcode: string;
  /**
   * Name
   *
   * The full name of the currency.
   */
  name: string;
  /**
   * Singular Form
   *
   * The singular form of the currency.
   */
  singular_form: string;
  /**
   * Plural Form
   *
   * The plural form of the currency.
   */
  plural_form: string;
};

/**
 * EditCurrencySchema
 */
export type EditCurrencySchema = {
  /**
   * Name
   *
   * The full name of the currency.
   */
  name: string;
  /**
   * Singular Form
   *
   * The singular form of the currency.
   */
  singular_form: string;
  /**
   * Plural Form
   *
   * The plural form of the currency.
   */
  plural_form: string;
};

/**
 * EditIntegrationSchema
 */
export type EditIntegrationSchema = {
  /**
   * Name
   *
   * The name of the integration.
   */
  name: string;
  /**
   * Description
   *
   * A description of the integration.
   */
  description: string;
  /**
   * Url
   *
   * URL to the website for the integration.
   */
  url: string | null;
};

/**
 * ErrorResponseSchema
 *
 * A generic error response.
 */
export type ErrorResponseSchema = {
  /**
   * Detail
   *
   * A description of the error.
   */
  detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * IntegrationSchema
 */
export type IntegrationSchema = {
  /**
   * Id
   *
   * The unique identifier of the integration.
   */
  id: string;
  /**
   * Name
   *
   * The name of the integration.
   */
  name: string;
  /**
   * Description
   *
   * A description of the integration.
   */
  description: string;
  /**
   * Url
   *
   * URL to the website for the integration.
   */
  url?: string | null;
  /**
   * Private
   *
   * Whether the integration is private.
   */
  private: boolean;
};

/**
 * IntegrationTokenSchema
 */
export type IntegrationTokenSchema = {
  /**
   * Id
   *
   * The unique identifier of the token.
   */
  id: string;
  /**
   * Name
   *
   * The name of the token.
   */
  name: string;
};

/**
 * SessionUser
 *
 * Details of the currently authenticated user.
 */
export type SessionUser = {
  /**
   * Id
   *
   * Discord snowflake of the authenticated user.
   */
  id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type GetCurrentUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/me';
};

export type GetCurrentUserResponses = {
  /**
   * Response Get Current User
   *
   * Successful Response
   */
  200: SessionUser | null;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type CreateCurrencyData = {
  body: CreateCurrencySchema;
  path?: never;
  query?: never;
  url: '/api/internal/currencies/';
};

export type CreateCurrencyErrors = {
  /**
   * Conflicting Shortcode
   */
  409: ErrorResponseSchema;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCurrencyError = CreateCurrencyErrors[keyof CreateCurrencyErrors];

export type CreateCurrencyResponses = {
  /**
   * Successful Response
   */
  201: CurrencySchema;
};

export type CreateCurrencyResponse = CreateCurrencyResponses[keyof CreateCurrencyResponses];

export type EditCurrencyData = {
  body: EditCurrencySchema;
  path: {
    /**
     * Shortcode
     */
    shortcode: string;
  };
  query?: never;
  url: '/api/internal/currencies/{shortcode}';
};

export type EditCurrencyErrors = {
  /**
   * Unauthorized
   */
  403: ErrorResponseSchema;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EditCurrencyError = EditCurrencyErrors[keyof EditCurrencyErrors];

export type EditCurrencyResponses = {
  /**
   * Successful Response
   */
  200: CurrencySchema;
};

export type EditCurrencyResponse = EditCurrencyResponses[keyof EditCurrencyResponses];

export type GetCurrencyPermissionsData = {
  body?: never;
  path: {
    /**
     * Shortcode
     */
    shortcode: string;
  };
  query?: never;
  url: '/api/internal/currencies/{shortcode}/permissions';
};

export type GetCurrencyPermissionsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCurrencyPermissionsError = GetCurrencyPermissionsErrors[keyof GetCurrencyPermissionsErrors];

export type GetCurrencyPermissionsResponses = {
  /**
   * Successful Response
   */
  200: CurrencyPermissionsSchema;
};

export type GetCurrencyPermissionsResponse = GetCurrencyPermissionsResponses[keyof GetCurrencyPermissionsResponses];

export type GetCurrencyIntegrationsData = {
  body?: never;
  path: {
    /**
     * Shortcode
     */
    shortcode: string;
  };
  query?: never;
  url: '/api/internal/currencies/{shortcode}/integrations';
};

export type GetCurrencyIntegrationsErrors = {
  /**
   * Unauthorized
   */
  403: ErrorResponseSchema;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCurrencyIntegrationsError = GetCurrencyIntegrationsErrors[keyof GetCurrencyIntegrationsErrors];

export type GetCurrencyIntegrationsResponses = {
  /**
   * Response Get Currency Integrations
   *
   * Successful Response
   */
  200: Array<IntegrationSchema>;
};

export type GetCurrencyIntegrationsResponse = GetCurrencyIntegrationsResponses[keyof GetCurrencyIntegrationsResponses];

export type ListIntegrationsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Manageable
     *
     * When true, returns only integrations the user can edit. Otherwise returns public integrations and integrations the user can connect.
     */
    manageable?: boolean;
  };
  url: '/api/internal/integrations/';
};

export type ListIntegrationsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListIntegrationsError = ListIntegrationsErrors[keyof ListIntegrationsErrors];

export type ListIntegrationsResponses = {
  /**
   * Response List Integrations
   *
   * Successful Response
   */
  200: Array<IntegrationSchema>;
};

export type ListIntegrationsResponse = ListIntegrationsResponses[keyof ListIntegrationsResponses];

export type CreateIntegrationData = {
  body: CreateIntegrationSchema;
  path?: never;
  query?: never;
  url: '/api/internal/integrations/';
};

export type CreateIntegrationErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateIntegrationError = CreateIntegrationErrors[keyof CreateIntegrationErrors];

export type CreateIntegrationResponses = {
  /**
   * Successful Response
   */
  201: IntegrationSchema;
};

export type CreateIntegrationResponse = CreateIntegrationResponses[keyof CreateIntegrationResponses];

export type GetIntegrationData = {
  body?: never;
  path: {
    /**
     * Integration Id
     */
    integration_id: string;
  };
  query?: never;
  url: '/api/internal/integrations/{integration_id}';
};

export type GetIntegrationErrors = {
  /**
   * Unauthorized
   */
  403: ErrorResponseSchema;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetIntegrationError = GetIntegrationErrors[keyof GetIntegrationErrors];

export type GetIntegrationResponses = {
  /**
   * Successful Response
   */
  200: IntegrationSchema;
};

export type GetIntegrationResponse = GetIntegrationResponses[keyof GetIntegrationResponses];

export type EditIntegrationData = {
  body: EditIntegrationSchema;
  path: {
    /**
     * Integration Id
     */
    integration_id: string;
  };
  query?: never;
  url: '/api/internal/integrations/{integration_id}';
};

export type EditIntegrationErrors = {
  /**
   * Unauthorized
   */
  403: ErrorResponseSchema;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EditIntegrationError = EditIntegrationErrors[keyof EditIntegrationErrors];

export type EditIntegrationResponses = {
  /**
   * Successful Response
   */
  200: IntegrationSchema;
};

export type EditIntegrationResponse = EditIntegrationResponses[keyof EditIntegrationResponses];

export type ListIntegrationTokensData = {
  body?: never;
  path: {
    /**
     * Integration Id
     */
    integration_id: string;
  };
  query?: never;
  url: '/api/internal/integrations/{integration_id}/tokens';
};

export type ListIntegrationTokensErrors = {
  /**
   * Unauthorized
   */
  403: ErrorResponseSchema;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListIntegrationTokensError = ListIntegrationTokensErrors[keyof ListIntegrationTokensErrors];

export type ListIntegrationTokensResponses = {
  /**
   * Response List Integration Tokens
   *
   * Successful Response
   */
  200: Array<IntegrationTokenSchema>;
};

export type ListIntegrationTokensResponse = ListIntegrationTokensResponses[keyof ListIntegrationTokensResponses];

export type CreateIntegrationTokenData = {
  body: CreateIntegrationTokenSchema;
  path: {
    /**
     * Integration Id
     */
    integration_id: string;
  };
  query?: never;
  url: '/api/internal/integrations/{integration_id}/tokens';
};

export type CreateIntegrationTokenErrors = {
  /**
   * Unauthorized
   */
  403: ErrorResponseSchema;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateIntegrationTokenError = CreateIntegrationTokenErrors[keyof CreateIntegrationTokenErrors];

export type CreateIntegrationTokenResponses = {
  /**
   * Successful Response
   */
  201: CreatedIntegrationTokenSchema;
};

export type CreateIntegrationTokenResponse = CreateIntegrationTokenResponses[keyof CreateIntegrationTokenResponses];

export type DeleteIntegrationTokenData = {
  body?: never;
  path: {
    /**
     * Integration Id
     */
    integration_id: string;
    /**
     * Token Id
     */
    token_id: string;
  };
  query?: never;
  url: '/api/internal/integrations/{integration_id}/tokens/{token_id}';
};

export type DeleteIntegrationTokenErrors = {
  /**
   * Unauthorized
   */
  403: ErrorResponseSchema;
  /**
   * Token Not Found
   */
  404: ErrorResponseSchema;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteIntegrationTokenError = DeleteIntegrationTokenErrors[keyof DeleteIntegrationTokenErrors];

export type DeleteIntegrationTokenResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type ConnectIntegrationData = {
  body: ConnectIntegrationSchema;
  path: {
    /**
     * Integration Id
     */
    integration_id: string;
  };
  query?: never;
  url: '/api/internal/integrations/{integration_id}/connect';
};

export type ConnectIntegrationErrors = {
  /**
   * Unauthorized
   */
  403: ErrorResponseSchema;
  /**
   * Integration Already Connected
   */
  409: ErrorResponseSchema;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ConnectIntegrationError = ConnectIntegrationErrors[keyof ConnectIntegrationErrors];

export type ConnectIntegrationResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};

export type DisconnectIntegrationData = {
  body: ConnectIntegrationSchema;
  path: {
    /**
     * Integration Id
     */
    integration_id: string;
  };
  query?: never;
  url: '/api/internal/integrations/{integration_id}/disconnect';
};

export type DisconnectIntegrationErrors = {
  /**
   * Unauthorized
   */
  403: ErrorResponseSchema;
  /**
   * Integration Not Connected
   */
  409: ErrorResponseSchema;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DisconnectIntegrationError = DisconnectIntegrationErrors[keyof DisconnectIntegrationErrors];

export type DisconnectIntegrationResponses = {
  /**
   * Successful Response
   */
  202: unknown;
};
