// This file is auto-generated by @hey-api/openapi-ts
import * as z from 'zod';

/**
 * ConnectIntegrationSchema
 */
export const zConnectIntegrationSchema = z.object({
  currency_shortcode: z.string(),
});

/**
 * CreateCurrencySchema
 */
export const zCreateCurrencySchema = z.object({
  shortcode: z.string().regex(/^[A-Z0-9]{3,5}$/),
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

/**
 * CreateIntegrationSchema
 */
export const zCreateIntegrationSchema = z.object({
  name: z.string(),
  description: z.string(),
  url: z.string().nullish(),
});

/**
 * CreateIntegrationTokenSchema
 */
export const zCreateIntegrationTokenSchema = z.object({
  name: z.string(),
});

/**
 * CreatedIntegrationTokenSchema
 */
export const zCreatedIntegrationTokenSchema = z.object({
  id: z.string(),
  name: z.string(),
  token: z.string(),
});

/**
 * CurrencyPermissionsSchema
 */
export const zCurrencyPermissionsSchema = z.object({
  edit: z.boolean().optional().default(false),
});

/**
 * CurrencySchema
 */
export const zCurrencySchema = z.object({
  shortcode: z.string(),
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

/**
 * EditCurrencySchema
 */
export const zEditCurrencySchema = z.object({
  name: z.string(),
  singular_form: z.string(),
  plural_form: z.string(),
});

/**
 * EditIntegrationSchema
 */
export const zEditIntegrationSchema = z.object({
  name: z.string(),
  description: z.string(),
  url: z.string().nullable(),
});

/**
 * ErrorResponseSchema
 *
 * A generic error response.
 */
export const zErrorResponseSchema = z.object({
  detail: z.string(),
});

/**
 * IntegrationSchema
 */
export const zIntegrationSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  url: z.string().nullish(),
  private: z.boolean(),
});

/**
 * IntegrationTokenSchema
 */
export const zIntegrationTokenSchema = z.object({
  id: z.string(),
  name: z.string(),
});

/**
 * SessionUser
 *
 * Details of the currently authenticated user.
 */
export const zSessionUser = z.object({
  id: z.string(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
  input: z.unknown().optional(),
  ctx: z.record(z.string(), z.unknown()).optional(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.array(zValidationError).optional(),
});

/**
 * Response Get Current User
 *
 * Successful Response
 */
export const zGetCurrentUserResponse = zSessionUser.nullable();

export const zCreateCurrencyBody = zCreateCurrencySchema;

/**
 * Successful Response
 */
export const zCreateCurrencyResponse = zCurrencySchema;

export const zEditCurrencyBody = zEditCurrencySchema;

export const zEditCurrencyPath = z.object({
  shortcode: z.string(),
});

/**
 * Successful Response
 */
export const zEditCurrencyResponse = zCurrencySchema;

export const zGetCurrencyPermissionsPath = z.object({
  shortcode: z.string(),
});

/**
 * Successful Response
 */
export const zGetCurrencyPermissionsResponse = zCurrencyPermissionsSchema;

export const zGetCurrencyIntegrationsPath = z.object({
  shortcode: z.string(),
});

/**
 * Response Get Currency Integrations
 *
 * Successful Response
 */
export const zGetCurrencyIntegrationsResponse = z.array(zIntegrationSchema);

export const zListIntegrationsQuery = z.object({
  manageable: z.boolean().optional().default(false),
});

/**
 * Response List Integrations
 *
 * Successful Response
 */
export const zListIntegrationsResponse = z.array(zIntegrationSchema);

export const zCreateIntegrationBody = zCreateIntegrationSchema;

/**
 * Successful Response
 */
export const zCreateIntegrationResponse = zIntegrationSchema;

export const zGetIntegrationPath = z.object({
  integration_id: z.string(),
});

/**
 * Successful Response
 */
export const zGetIntegrationResponse = zIntegrationSchema;

export const zEditIntegrationBody = zEditIntegrationSchema;

export const zEditIntegrationPath = z.object({
  integration_id: z.string(),
});

/**
 * Successful Response
 */
export const zEditIntegrationResponse = zIntegrationSchema;

export const zListIntegrationTokensPath = z.object({
  integration_id: z.string(),
});

/**
 * Response List Integration Tokens
 *
 * Successful Response
 */
export const zListIntegrationTokensResponse = z.array(zIntegrationTokenSchema);

export const zCreateIntegrationTokenBody = zCreateIntegrationTokenSchema;

export const zCreateIntegrationTokenPath = z.object({
  integration_id: z.string(),
});

/**
 * Successful Response
 */
export const zCreateIntegrationTokenResponse = zCreatedIntegrationTokenSchema;

export const zDeleteIntegrationTokenPath = z.object({
  integration_id: z.string(),
  token_id: z.string(),
});

export const zConnectIntegrationBody = zConnectIntegrationSchema;

export const zConnectIntegrationPath = z.object({
  integration_id: z.string(),
});

export const zDisconnectIntegrationBody = zConnectIntegrationSchema;

export const zDisconnectIntegrationPath = z.object({
  integration_id: z.string(),
});
